services:
  extractor:
    container_name: extractor
    build:
      context: .
      dockerfile: app/extractor/Dockerfile
    volumes:
      - cloudwalk_volume:/usr/src/cloudwalk/app/database

  querier:
    container_name: querier
    build:
      context: .
      dockerfile: app/query/Dockerfile
    volumes:
      - cloudwalk_volume:/usr/src/cloudwalk/app/database
    depends_on:
      extractor:
        condition: service_completed_successfully

volumes:
  cloudwalk_volume:
    external: true
