services:
  base:
    build: .
    image: cloudwalk-image
    command: echo "Base image started"

  extractor:
    container_name: extractor
    image: cloudwalk-image
    command: python -m app.extractor.extract
    volumes:
      - cloudwalk_volume:/usr/src/cloudwalk/app/database

  querier:
    container_name: querier
    image: cloudwalk-image
    command: python -m app.query.query
    volumes:
      - cloudwalk_volume:/usr/src/cloudwalk/app/database
    depends_on:
      extractor:
        condition: service_completed_successfully

volumes:
  cloudwalk_volume:
    external: true
